#!/bin/bash

#2.
INSERT INTO EMP (EMPNO,ENAME,JOB) VALUES (1,'Jean','SALESMAN');
INSERT INTO EMP (EMPNO,ENAME,JOB) VALUES (2,'Michel','SALESMAN');
INSERT INTO EMP (EMPNO,ENAME,JOB) VALUES (3,'Jacques','SALESMAN');

